const talents=[{n:"سارة العلوي",r:"مصممة UI/UX",v:"س",p:"$35 / ساعة"},{n:"يوسف بناني",r:"Full-stack Developer",v:"ي",p:"$42 / ساعة"},{n:"مريم آيت",r:"كاتبة ومختصة SEO",v:"م",p:"$25 / ساعة"},{n:"آدم رشيد",r:"Video & Motion Designer",v:"أ",p:"$38 / ساعة"}];
const grid=document.getElementById("talentGrid");
grid.innerHTML=talents.map(t=>`<article class="talent"><div class="avatar">${t.v}</div><h3>${t.n}</h3><p>${t.r}</p><span class="stars">★★★★★</span><span style="color:#91a3b8;font-size:11px"> 4.9 • +80 مشروع</span><div class="price"><span>يبدأ من</span><b>${t.p}</b></div></article>`).join("");
const modal=document.getElementById("modal"), content=document.getElementById("modalContent");
function openModal(title,body){content.innerHTML=`<h2>${title}</h2>${body}`;modal.classList.remove("hidden")}
document.getElementById("closeModal").onclick=()=>modal.classList.add("hidden");
modal.onclick=e=>{if(e.target===modal)modal.classList.add("hidden")};
document.getElementById("joinBtn").onclick=()=>openModal("ابدأ مع Store World",`<p style="color:#91a3b8">أنشئ حسابك المجاني وابدأ كعميل أو مستقل.</p><label>البريد الإلكتروني</label><input type="email" placeholder="you@example.com"><button class="primary" style="width:100%">إنشاء حساب</button>`);
document.getElementById("loginBtn").onclick=()=>openModal("تسجيل الدخول",`<label>البريد الإلكتروني</label><input type="email"><label>كلمة المرور</label><input type="password"><button class="primary" style="width:100%">دخول</button>`);
document.getElementById("ctaBtn").onclick=()=>document.getElementById("joinBtn").click();
document.getElementById("aiBtn").onclick=()=>openModal("AI Hub",`<p style="color:#91a3b8">اختر المهمة التي تريد إنجازها.</p><div class="ai-tags"><span>كتابة وتحسين نص</span><span>تلخيص مشروع</span><span>صياغة عرض</span><span>تحسين بروفايل</span><span>وصف خدمة</span><span>تحسين brief</span></div><textarea rows="4" placeholder="اكتب ما تريد من المساعد..."></textarea><button class="primary">تشغيل المساعد</button>`);
document.getElementById("searchBtn").onclick=()=>{const q=document.getElementById("heroSearch").value.trim();openModal("نتيجة البحث",q?`<p>سنبحث عن <b>${q}</b> ونقترح الخدمات والمواهب الأنسب.</p><button class="primary" onclick="document.getElementById('modal').classList.add('hidden');location.hash='marketplace'">استكشف السوق</button>`:"اكتب ما تريد إنجازه أولًا.");};
document.querySelectorAll(".chips button").forEach(b=>b.onclick=()=>{document.getElementById("heroSearch").value=b.textContent;document.getElementById("searchBtn").click()});
document.querySelectorAll("[data-view]").forEach(a=>a.addEventListener("click",e=>{const v=a.dataset.view;if(v==="marketplace")document.getElementById("marketplace").scrollIntoView();else if(v==="talent")document.getElementById("talent").scrollIntoView();else if(v==="ai")document.getElementById("ai").scrollIntoView();else if(v==="how")document.getElementById("how").scrollIntoView();else window.scrollTo({top:0,behavior:"smooth"})}));
document.querySelectorAll(".category").forEach(b=>b.onclick=()=>openModal("استكشاف الخدمات",`<p>فئة <b>${b.querySelector("b").textContent}</b> جاهزة للاستكشاف.</p><button class="primary" onclick="document.getElementById('modal').classList.add('hidden')">عرض الخدمات</button>`));
document.getElementById("langBtn").onclick=()=>openModal("English version",`<p style="color:#91a3b8">واجهة الإنجليزية ستكون متاحة كتبديل كامل في النسخة القادمة.</p>`);
